name: Deploy to staging
on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploy everything to the staging cluster
    runs-on: ubuntu-latest 

    steps:

      - name: SSH Into Server and Deploy
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh  # Secure the directory
          # Create SSH key file
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key

          # Add server to known hosts (prevents SSH confirmation prompt)
          ssh-keyscan -H 51.21.152.6 >> ~/.ssh/known_hosts

          # Connect to server and execute commands
          ssh -i ~/ssh_key -o StrictHostKeyChecking=no ubuntu@51.21.152.6 << 'EOF'
            cd deploy_practice/
            git pull
            pnpm install
            pnpm run build
            pm2 restart fe-server
            pm2 restart ws-server
            pm2 restart http-server
          EOF
