name: Deploy to staging
on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploy everything to the staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: SSH Into Server and Deploy
        run: |
          # Create SSH key file safely
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          
          # Ensure known_hosts file exists
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

          # Connect to server and execute deployment
          ssh -i ~/ssh_key -o StrictHostKeyChecking=no ubuntu@51.21.152.6 << 'EOF'
            source ~/.bashrc
            source ~/.profile
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            cd deploy_practice/
            git pull
            pnpm install
            pnpm run build

            # Check if PM2 processes exist before restarting
          cd apps/web && pm2 start npm --name fe-server -- start
          cd ../ws-server && pm2 start npm --name ws-server -- start
          cd ../http-server && pm2 start npm --name http-server -- start


            # Restart them after ensuring they exist
            pm2 restart fe-server
            pm2 restart ws-server
            pm2 restart http-server
          EOF