name: Deploy to staging
on:
    push:
        branches:
            - "main"

jobs:
    redeploy_everything:
        name: deploy everything to the staging cluster
        runs-on: ubuntu-latest 

        steps:
            - name: SSH Into Server
              run: |
                echo ${{secrets.SSH_PRIVATE_KEY}} &> ~ssh_key
                ssh -i ~/ssh_key ubuntu@51.21.152.6
                cd deploy_practice/ && git pull
                pnpm install
                pnpm run build
                pm2 restart fe-server
                pm2 restart ws-server
                pm2 restart http-server