name: Deploy to staging
on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploy everything to the staging cluster
    runs-on: ubuntu-latest 

    steps:
      - name: SSH Into Server and Deploy
        run: |
          # Create SSH key file safely
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          
          # Ensure known_hosts file exists
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

          # Connect to server and execute deployment
          ssh -i ~/ssh_key -o StrictHostKeyChecking=no ubuntu@51.21.152.6 << 'EOF'
          export PATH=$HOME/.nvm/versions/node/v22.14.0/bin:$PATH
          cd deploy_practice/
          git pull
          pnpm install
          pnpm run build
          pm2 restart fe-server
          pm2 restart ws-server
          pm2 restart http-server
          EOF
